### ISSUE TITLE
After downloading and enabling coder_review all ops on /admin/modules are 'code review'.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/coder_review#5]
* I downloaded to `modules/contrib/coder_review`
* enabled `coder_review`
* the `ops` column on `/admin/module` are now all `code review`

<img width="1496" alt="screen shot 2017-05-28 at 1 43 28 pm" src="https://cloud.githubusercontent.com/assets/6763671/26530885/11ea1cd2-43ac-11e7-9629-1fcb5125c2df.png">

**Comment by docwilmot** [comment]
Yep, noted. And the search filter stops working. Thanks.

**Comment by docwilmot** [comment]
Fixed

**Comment by oadaeh** [comment]
Where was this fixed?
I'm still seeing this behavior (and some other possibly related problems) in the downloaded code from https://backdropcms.org/project/coder_review and both the cs & review branches here.
When I disable Coder Review, all goes back to normal, so I don't think it's a caching problem, though I did clear them all.

**Comment by docwilmot** [comment]
problem is the branching of this is a mess. this was fixed in my github repo 'review' branch but never merged. https://github.com/docwilmot/coder_review/commits/review. pushed new default branch 1.x-1.x. 

Also new release.

**Comment by oadaeh** [comment]
Thanks @docwilmot.
